import { PaymentDetails } from "./_components/details";


export const metadata = {
    title: "Payment Student...",
    description: "Generated by create next app",
};

export default function Sponsor() {
    return (
        <div className="bg-[#fff] md:rounded-[6px] lg:rounded-[6px] md:m-4 lg:m-4">
            <PaymentDetails />
        </div>
    )
}